# Generated by Django 2.2.20 on 2021-09-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patner',
            old_name='image',
            new_name='imagee',
        ),
    ]
